// Auto-generated by build_vm_profiles.py - DO NOT EDIT MANUALLY
// This file contains obfuscated key material for VM profiles database
// Generated: Sun Dec 21 18:58:29 UTC 2025
//
// SECURITY NOTE: This obfuscation protects against simple extraction methods.
// For maximum security, ensure the binary is not distributed to untrusted parties.

#ifndef OWL_VM_DB_KEY_H_
#define OWL_VM_DB_KEY_H_

#include <cstdint>
#include <cstddef>
#include <string>
#include <vector>

namespace owl {
namespace vm_db {

// Obfuscation key (XOR mask)
static const uint8_t kObfuscatedMask[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00
};
static const size_t kObfuscatedMaskSize = 16;

// Key parts (obfuscated) - used for integrity verification
static const uint8_t kObfuscatedPart1[] = {
    0xb9, 0xba, 0xae, 0x86, 0x4e, 0x6e, 0xc3, 0x98, 0x0c, 0x5b, 0x8c, 0xc5,
    0x37, 0x16, 0x2f, 0x04
};
static const size_t kObfuscatedPart1Size = 16;

static const uint8_t kObfuscatedPart2[] = {
    0x31, 0xe6, 0x8c, 0x22, 0x8d, 0x7e, 0x2a, 0x27, 0xc2, 0x80, 0xa3, 0x6c,
    0xfd, 0x9d, 0xbe, 0x57
};
static const size_t kObfuscatedPart2Size = 16;

static const uint8_t kObfuscatedPart3[] = {
    0x88, 0x65, 0xaa, 0x76, 0xc4, 0xe9, 0x11, 0x2b, 0x92, 0x4b, 0xad, 0x8f,
    0xda, 0x59, 0x3e, 0x22
};
static const size_t kObfuscatedPart3Size = 16;

// Obfuscated database password
static const uint8_t kObfuscatedPassword[] = {
    0x2f, 0x43, 0x1f, 0xb4, 0x22, 0x3c, 0xf8, 0x0d, 0x09, 0xfd, 0x71, 0x84,
    0x6c, 0x8a, 0x66, 0xea, 0x7b, 0x18, 0x49, 0xbb, 0x79, 0x3b, 0xfe, 0x5c,
    0x5e, 0xae, 0x22, 0x84, 0x3b, 0xd6, 0x30, 0xbc, 0x28, 0x4f, 0x1b, 0xe9,
    0x2b, 0x6e, 0xf9, 0x0a, 0x59, 0xa9, 0x24, 0x86, 0x3a, 0x84, 0x30, 0xbb,
    0x78, 0x43, 0x1d, 0xbe, 0x29, 0x3a, 0xad, 0x59, 0x5e, 0xf1, 0x70, 0x86,
    0x39, 0xd6, 0x6e, 0xea
};
static const size_t kObfuscatedPasswordSize = 64;

// Deobfuscation helper
inline std::vector<uint8_t> Deobfuscate(const uint8_t* data, size_t data_size,
                                         const uint8_t* mask, size_t mask_size) {
    std::vector<uint8_t> result(data_size);
    for (size_t i = 0; i < data_size; ++i) {
        result[i] = data[i] ^ mask[i % mask_size];
    }
    return result;
}

// Get the deobfuscated mask first (meta-obfuscation)
inline std::vector<uint8_t> GetMask() {
    // The mask itself is XOR'd with a compile-time constant
    static const uint8_t kMetaMask[] = {
        0x4D, 0x7A, 0x2F, 0x8C, 0x1B, 0x5E, 0x9A, 0x3D,
        0x6F, 0xC8, 0x41, 0xE7, 0x0A, 0xB3, 0x56, 0xD9
    };
    return Deobfuscate(kObfuscatedMask, kObfuscatedMaskSize, kMetaMask, sizeof(kMetaMask));
}

// Get the database password
inline std::string GetDatabasePassword() {
    auto mask = GetMask();
    auto password = Deobfuscate(kObfuscatedPassword, kObfuscatedPasswordSize,
                                 mask.data(), mask.size());
    return std::string(password.begin(), password.end());
}

}  // namespace vm_db
}  // namespace owl

#endif  // OWL_VM_DB_KEY_H_
