#pragma once

#include <string>
#include <vector>
#include "include/cef_browser.h"
#include "include/cef_frame.h"
#include "owl_demographics.h"

// Natural Language Action (NLA) System
// Converts natural language commands into browser actions using on-device LLM

// Single atomic action
struct NLAction {
  std::string type;        // "navigate", "click", "type", "wait", "screenshot", "extract"
  std::string target;      // Element description or URL
  std::string value;       // Text to type (for type action)
  int timeout_ms;          // For wait action
  bool completed;          // Execution status
  std::string result;      // Result or error message
};

// Action plan generated by LLM
struct NLActionPlan {
  std::vector<NLAction> actions;
  std::string reasoning;   // LLM's reasoning for the plan
  bool success;
  std::string error;
};

// Page state snapshot for LLM context
struct PageState {
  std::string url;
  std::string title;
  std::string visible_text;         // First 1500 chars
  std::vector<std::string> interactive_elements;  // Buttons, links, inputs
  std::vector<std::string> input_fields;          // All input elements
  DemographicInfo demographics;     // User context: location, time, weather
};

class OwlNLA {
public:
  // Main entry point: Execute natural language command
  // Example: "go to google.com and search for banana"
  static std::string ExecuteCommand(
      CefRefPtr<CefFrame> frame,
      const std::string& command);

  // Automation overlay helpers (public for Developer Playground)
  static void ShowAutomationOverlay(CefRefPtr<CefFrame> frame);
  static void UpdateAutomationStep(CefRefPtr<CefFrame> frame, int current, int total, const std::string& step_description, double step_time_ms, double total_time_ms);
  static void HideAutomationOverlay(CefRefPtr<CefFrame> frame);

private:
  // Step 1: Get current page state for LLM context
  static PageState GetPageState(CefRefPtr<CefFrame> frame);

  // Step 2: Use LLM to create action plan from natural language
  static NLActionPlan PlanActions(
      const std::string& command,
      const PageState& current_state);

  // Step 3: Execute each action in the plan
  static bool ExecuteAction(
      CefRefPtr<CefFrame> frame,
      NLAction& action);

  // Step 4: Verify action succeeded
  static bool VerifyAction(
      CefRefPtr<CefFrame> frame,
      const NLAction& action);

  // Helper: Convert action plan to JSON for logging
  static std::string ActionPlanToJSON(const NLActionPlan& plan);

  // Helper: Serialize page state for LLM prompt
  static std::string PageStateToXML(const PageState& state);

  // Action executors for each primitive
  static bool ExecuteNavigate(CefRefPtr<CefFrame> frame, NLAction& action);
  static bool ExecuteClick(CefRefPtr<CefFrame> frame, NLAction& action);
  static bool ExecuteType(CefRefPtr<CefFrame> frame, NLAction& action);
  static bool ExecuteWait(CefRefPtr<CefFrame> frame, NLAction& action);
  static bool ExecuteScreenshot(CefRefPtr<CefFrame> frame, NLAction& action);
  static bool ExecuteExtract(CefRefPtr<CefFrame> frame, NLAction& action);
};
